### ISSUE TITLE
Conflict with requestInterceptors in restangular.withConfig

### ISSUE THREAD

**Issue by eroak** [2muchcoffeecom/ngx-restangular#100]
Hi,

It seems that `config.requestInterceptors` is shared (and not cloned) between all configured restangular instances.

### 1. How to reproduce :

- Create a configured restangular instance
- Create a second configured restangular instance and add an interceptor with `config.addFullRequestInterceptor()` which logs something
- Whatever the used restangular configured instance, the log is printed

### 2. Workarround :

In your config factories, clone the `config.requestInterceptors` before adding your specific interceptors :

```
return restangular.withConfig(RestangularConfigurer => {
    RestangularConfigurer.requestInterceptors = Array.from(RestangularConfigurer.requestInterceptors);
    RestangularConfigurer.addFullRequestInterceptor((element, operation, path, url, headers, params) => {
      console.log('foobar');
      return;
    });
 });
```

**Comment by n-weber** [comment]
Well, this seems confusing indeed.

Restangular seems to be a REST API requester in a nutshell.

But what if you have two different needs in your app?
Let's say that you have an authorization API and a resource API, each of them on different domains and routes.
Configuring two different Restangular instances (through the `restangular.withConfig()` method), I'd like to add some Authorization header for the auth API only and then some API key on the resource API only.

That would be really handy to configure specific request interceptors on each restangular config so that none of them will leak and pollute the global config.

BTW, thanks @eroak for the workaround.

**Comment by rshchpkn** [comment]
Hello @eroak, The second instance of restangular is extending existing restangular instance. That was the behavior of the restangular for angularjs.
