### ISSUE TITLE
Update name of the project

### ISSUE THREAD

**Issue by tamascsaba** [2muchcoffeecom/ngx-restangular#17]
Angular4 will be released at 2017 march. I think it will be good rename the project to ngx-restangular or ngx-rest or something else.

![angular4-tentativeschedule](https://cloud.githubusercontent.com/assets/3479963/21852251/a8704f88-d812-11e6-897d-010bd9cc1031.png)

**Comment by tairezzzz** [comment]
@tamascsaba Thanks for pointing for this out. We're considering this possibility since https://twitter.com/AngularBorscht/status/814604136079626241 and https://twitter.com/tairezzzz/status/810225874868064256 But I still thinking that we should do this a little bit later, when whole audience stops searching for ng2- modules

**Comment by tairezzzz** [comment]
@tamascsaba We've renamed project to ngx-restangular :)
