### ISSUE TITLE
How could I download a file

### ISSUE THREAD

**Issue by fabianedl777** [2muchcoffeecom/ngx-restangular#82]
I am trying to download a file but I can not perform this action is it possible to download a file?

**Comment by nowzig** [comment]
It seems not to be possible, because you cannot set ResponseType to blob [here](https://github.com/2muchcoffeecom/ngx-restangular/blob/7ffda9bb32740ef7acbdbc31e088cf4a52958cda/src/ngx-restangular-helper.ts#L11) and therefore the responded data is handled as a String, with the normal JSON parsing.

In a response with blob data I get the error in this [line](https://github.com/2muchcoffeecom/ngx-restangular/blob/7ffda9bb32740ef7acbdbc31e088cf4a52958cda/src/ngx-restangular-http.ts#L29), as it is trying to parse the data as JSON.

**Comment by logvinoleg89** [comment]
@fabianedl777 now there is no opportunity to get the file. Mostly probably it will be possible soon.
